### ISSUE TITLE
An error during program execution

### ISSUE THREAD

**Issue by mahlamahdi** [ilonatommy/DLR_FacialEmotionRecognition#1]
Hi, i am mahla and i decide to run your source code in colab.
but  An error occurs while running the program that I can't solve it.
error:

Traceback (most recent call last):
  File "Program.py", line 36, in <module>
    X_train, X_test, y_train, y_test = dl.load_train_test_split()
  File "/content/DataLoader.py", line 55, in load_train_test_split
    X_train = np.load(os.path.join(self.splitDatasetsDir, 'X_train_size' + self.datasetInfo + '.npy'))
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'splitDatasets75/X_train_size_75_limit_10.npy'

**Comment by ilonatommy** [comment]
Thank you Mahla for your feedback. This was a study project and as I can see, I did not translate the report to English. It seems you are missing data files. Training data are generally big and I did not commit them to the repo. They come from: 
https://grail.cs.washington.edu/projects/deepexpr/ferg-2d-db.html and I mentioned it in the report but I understand that it was hard for you to find this information:
https://github.com/ilonatommy/DLR_FacialEmotionRecognition/blob/master/documents/Raport%20Projekt.pdf.
I will come back to you once I have more time to check how exactly I was preprocessing the data to load them.

**Comment by umaiskhan42** [comment]
same issue im facing, even though i have downloaded the dataset and set their paths correctly.

**Comment by umaiskhan42** [comment]
> Hi, i am mahla and i decide to run your source code in colab. but An error occurs while running the program that I can't solve it. error:
> 
> Traceback (most recent call last): File "Program.py", line 36, in X_train, X_test, y_train, y_test = dl.load_train_test_split() File "/content/DataLoader.py", line 55, in load_train_test_split X_train = np.load(os.path.join(self.splitDatasetsDir, 'X_train_size' + self.datasetInfo + '.npy')) File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 417, in load fid = stack.enter_context(open(os_fspath(file), "rb")) FileNotFoundError: [Errno 2] No such file or directory: 'splitDatasets75/X_train_size_75_limit_10.npy'

Hey, i have resolved this issue, you can view my code snippet of dataloader as:
class DataLoader:
    def __init__(self, path, extension, classes, img_size, limit):
        self.path = path
        self.extension = str(extension)
        self.classes = classes
        self.img_size = img_size
        self.limit = limit
        self.datasetInfo = '_' + str(self.img_size) + '_limit_' + str(self.limit)
        self.splitDatasetsDir = 'splitDatasets' + str(img_size)
        self.modelsDir = 'models'
        self.resultsDir = 'out'
        os.makedirs(self.splitDatasetsDir, exist_ok=True)
        os.makedirs(self.modelsDir, exist_ok=True)
        os.makedirs(self.resultsDir, exist_ok=True)
# rest of the code is same
